# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install docker
      uses: docker-practice/actions-setup-docker@master
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}
        registry: ghcr.io
    - name: Maven Build
<<<<<<< HEAD
      run: mvn -B clean deploy --file pom.xml -s apache_settings.xml
=======
      run: mvn -B clean install --file pom.xml -s apache_settings.xml
    - name: Deploy Docker Images
      run: mvn -B clean package --file ./images/pom.xml -s apache_settings.xml
>>>>>>> b7a8fa7d0055a599e9f37ac4e613401b542893f1
